{"name": "test_restore_non_existent_author", "status": "passed", "description": "\n    Test PATCH /authors/:id/restore endpoint with non-existent ID.\n\n    Returns:\n        404 NOT FOUND\n\n    Scenario:\n        - Attempt to restore an author that does not exist\n    ", "start": 1731478751025, "stop": 1731478751026, "uuid": "aa53ec4f-4295-4b09-adad-076cd41a1c58", "historyId": "5c1237e99bfa1ef6f1a129dd7cc506fe", "testCaseId": "5c1237e99bfa1ef6f1a129dd7cc506fe", "fullName": "tests.test_authors#test_restore_non_existent_author", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authors"}, {"name": "host", "value": "LAPTOP-FCSAI6EF"}, {"name": "thread", "value": "27016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authors"}]}